name = "abeja-tracker"
main = "worker/index.ts"
compatibility_date = "2026-08-25"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "LOGS"
id = "fd1d96c0983c4b3d9faa9c857d93f36f"
